spring.application.name=FieldServiceManagement
server.port = 9090
spring.datasource.url = jdbc:mysql://localhost:3306/feildservicemanagement
spring.datasource.username = root
spring.datasource.password = 2629
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect


#Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=govindpatidar4214@gmail.com
spring.mail.password=xeqk jkig suwy psbv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
